application: gateway_proxy
version: 1
runtime: go114
api_version: go1

server:
  port: 8000
database:
  type: mysql
  user: root
  password: root1234
  host: 127.0.0.1:3306
  dbname: db_gateway_proxy
  charset: utf8
redis:
  host: 172.16.1.120:16379
  password:
  db: 0

handlers:
  - url: /.*
    script: _go_app