application: gateway_proxy
version: 1
runtime: go114
api_version: go1

server:
  port: 8080
database:
  type: mysql
  user: root
  password: root1234
  host: 172.16.39.19:3306
  dbname: db_gateway_proxy
  charset: utf8
redis:
  host: 172.16.1.120:16379
  password:
  db: 0
log:
  #相对于项目部署目录的路径 => project_dir/log
  #或者绝对路径目录
  path: log

handlers:
  - url: /.*
    script: _go_app