application: gateway_proxy
version: 1
runtime: go114
api_version: go1

server:
  port: 8080
database:
  type: mysql
  user: root
  password: root1234
  host: 172.16.39.19:3306
  dbname: db_gateway_proxy
  charset: utf8
redis:
  host: 172.16.1.120:16379
  password:
  db: 0
log:
  #相对于项目部署目录的路径 => project_dir/log
  #或者绝对路径目录
  path: log/

eureka:
  serviceUrl:
    defaultZone: http://172.16.1.155:8761/eureka/
  client:
    #指示从eureka服务器获取注册表信息的频率（s）
    registryFetchIntervalSeconds: 30
    #客户端是否获取eureka服务器注册表上的注册信息,不调用其他微服务可以为false，默认为false
    fetchRegistry: true
    #是否过滤掉非up实例，默认为false
    filterOnlyUpInstances: true
    #指示此实例是否应将其信息注册到eureka服务器以供其他服务发现，默认为false
    registerWithEureka: true
    #client在shutdown情况下，是否显示从注册中心注销
    shouldUnregisterOnShutdown: true
    #http代理
    proxy: http://172.16.1.120:8118
    ####
    #读取Eureka Server 超时时间（s），默认8秒
    eurekaServerReadTimeoutSeconds: 8
    #连接到 Eureka Server 空闲连接的超时时间（s），默认30
    eurekaConnectionIdleTimeoutSeconds: 30
    #获取从eureka客户端到eureka服务器主机允许的连接总数，默认50个
    eurekaServerTotalConnectionsPerHost: 50
    #每个host的idle状态的最大连接数目
    eurekaServerTotalIdleConnectionsPerHost: 5
    #获取从eureka客户端到所有eureka服务器的连接总数,默认200个
    eurekaServerTotalIdleConnections: 200
    #####
    #指示eureka客户端是否应使用DNS机制来获取要与之通信的eureka服务器列表。当DNS名称更新为具有其他服务器时，eureka客户端轮询eurekaServiceUrlPollIntervalSeconds中指定的信息后立即使用该信息。
    use-dns-for-fetchingService-urls: false
  instance:
    #该服务实例在注册中心的唯一实例ID,为空则默认本地ip和服务端口
    #instanceId: ${spring.cloud.client.ip-address}:${server.port}
    #注册到注册中心的应用所属分组名称（AWS服务器）
    appName: gateway-proxy
    #是否优先使用服务实例的IP地址，相较于hostname
    preferIpAddress: true
    nonSecurePort: 8080
    nonSecurePortEnabled: true
    #HTTPS通信端口
    securePort: 443
    #是否启用HTTPS通信端口
    securePortEnabled: false
    #服务实例安全主机名称（HTTPS）
    secureVirtualHostName:
    #该服务实例非安全注解名称（HTTP）
    virtualHostName:
    ############
    ###
    ###########
    #该服务实例的状态检查地址，相对地址
    statusPageUrlPath: /actuator/info
    #该服务实例的主页地址，相对地址
    homePageUrlPath: /
    #该服务实例的健康检查地址，相对地址
    healthCheckUrlPath: /actuator/health
    ############
    ###
    ###########
    countryId: 0
    #指定服务实例所属数据中心
    #dataCenterInfo:
    #  name: MyOwn
    #  metadata:
    #    amiLaunchIndex:
    #    localHostname:
    #    availabilityZone:
    #    instanceId:
    #    publicIpv4:
    #    publicHostname:
    #    amiManifestPath:
    #    localIpv4:
    #    hostname:
    #    amiId:
    #    instanceType:
    metadata:
      xxx: xxx
      acc: xxx
    leaseInfo:
      #该服务实例向注册中心发送心跳间隔（30s）
      renewalIntervalInSecs: 5
      #指示eureka服务器在删除此实例之前收到最后一次心跳之后等待的时间（900s）
      durationInSecs: 10
    #指示是否应在eureka注册后立即启用实例以获取流量，不建议立即开启
    instanceEnabledOnInit: false

handlers:
  - url: /.*
    script: _go_app